import{i as x,a as W,r as H,T as q,g as f}from"./assets/switch-button-b5212124.js";import{i as z}from"./assets/vendor-f87d3a68.js";const O=[{title:"Save the Children",url:"https://www.savethechildren.net/what-we-do/emergencies/ukraine-crisis",img:null},{title:"Project HOPE",url:"https://www.projecthope.org/country/ukraine/",img:null},{title:"UNITED24",url:"https://u24.gov.ua/uk",img:null},{title:"International Medical Corps",url:"https://internationalmedicalcorps.org/country/ukraine/",img:null},{title:"Medicins Sans Frontieres",url:"https://www.msf.org/ukraine",img:null},{title:"RAZOM",url:"https://www.razomforukraine.org/",img:null},{title:"Action against hunger",url:"https://www.actionagainsthunger.org/location/europe/ukraine/",img:null},{title:"World vision",url:"https://www.wvi.org/emergencies/ukraine",img:null},{title:"Serhiy Prytula Charity Foundation",url:"https://prytulafoundation.org/en",img:null}];let T=document.querySelector(".plus-btn"),$=document.querySelector(".second-btn");const C=document.querySelectorAll(".header-link");document.querySelectorAll(".header-item");for(let e=0;e<C.length;e++)C[e].setAttribute("href",`${O[e].url}`);T.addEventListener("click",function(){T.style.display="none",$.style.display="flex";const e=document.querySelectorAll(".header-item");for(let o=0;o<3;o++)e[o].style.display="none"});$.addEventListener("click",function(){T.style.display="flex",$.style.display="none";const e=document.querySelectorAll(".header-item");for(let o=0;o<3;o++)e[o].style.display="flex"});const B=document.querySelector("body"),r=document.querySelector(".modal"),w=document.querySelector(".backdrop"),_=document.querySelector(".modal-close-btn"),a=document.querySelector(".modal-list-btn-add"),u=document.querySelector(".modal-list-btn-remove"),b=document.querySelector(".modal-list-container");let M;async function j(e){u.setAttribute("id",`${e}`),M=e,document.addEventListener("keydown",I);const o=await f(M);F(o);try{const s=x(q);for(const i of s)i.constID===e&&(a.style.display="none",u.style.display="flex",b.innerText="Сongratulations! You have added the book to the shopping list. To delete, press the button “Remove from the shopping list”.",window.innerWidth<=768?r.style.height="806px":r.style.height="501px")}catch{}a.addEventListener("click",L),u.addEventListener("click",S)}function F(e){var l,p;w.style.display="flex",B.style.overflow="hidden";const o=((l=e.buy_links.find(t=>t.name==="Amazon"))==null?void 0:l.url)||"",s=((p=e.buy_links.find(t=>t.name==="Apple Books"))==null?void 0:p.url)||"",i=e.description?e.description:"With our diverse range of titles, you're sure to find the perfect companion for cozy nights in. Treat yourself to the joy of reading and explore the endless possibilities that await within the pages of our books.",m=`
  <ul class="buy-links-list">
    <li>
      <img class="img-amazon" src="./images/amazon.png" alt="Amazon" class="platform-image" data-url="${o}">
    </li>
    <li>
      <img class="img-apple" src="./images/book.png" alt="Apple Books" class="platform-image" data-url="${s}">
    </li>
  </ul>
`;r.innerHTML=`
  <div class="modal-container">
  <img src="${e.book_image}" class="modal-image">
    <div class="modal-wrap">
      <h2 class="modal-title">${e.title}</h2>
      <p class="modal-author">${e.author}</p>
      <p class="description-modal">${i}</p>
      ${m}
    </div>  
  </div>
`,r.appendChild(_),r.appendChild(a),r.appendChild(u),r.appendChild(b),r.querySelectorAll(".platform-image").forEach(t=>{t.addEventListener("click",()=>{const n=t.dataset.url;n?window.open(n,"_blank"):console.error("Platform URL not found.")})})}document.addEventListener("DOMContentLoaded",function(){_.addEventListener("click",function(){A()}),w.addEventListener("click",function(e){e.target===w&&A()})});a.addEventListener("click",function(){b.innerText="Сongratulations! You have added the book to the shopping list. To delete, press the button “Remove from the shopping list”.",window.innerWidth<=768?r.style.height="806px":r.style.height="501px",a.removeEventListener("click",this)});u.addEventListener("click",function(){b.innerText="",window.innerWidth<=768?r.style.height="762px":r.style.height="465px",u.removeEventListener("click",this)});function I(e){e.key==="Escape"&&(A(),document.removeEventListener("keydown",I))}function A(){r.classList.add("closing"),setTimeout(function(){w.style.display="none",r.classList.remove("closing")},500),a.removeEventListener("click",L),a.removeEventListener("click",S),B.style.overflow="auto",a.style.display="flex",u.style.display="none"}function L(){const e=x(q)||[];e.push({constID:M}),W(q,e),a.style.display="none",u.style.display="flex",a.removeEventListener("click",L),u.addEventListener("click",S)}function S(e){H(e),a.style.display="flex",u.style.display="none",a.removeEventListener("click",S),a.addEventListener("click",L)}const P="category";async function D(e){const o=document.querySelector(".js-booksgallery");o.innerHTML="";try{const i=await f(P,e);R(i),U(e)}catch(i){console.error("Failed to fetch books:",i)}document.querySelectorAll(".cat-book-image-overlay").forEach(i=>{i.addEventListener("click",m=>{const l=m.target.closest(".booksgallery-item");if(l){const p=l.dataset.id;j(p)}})})}function R(e){const o=document.querySelector(".booksgallery"),s=e.map(i=>`
      <li class="booksgallery-item cardCategory book-hover" data-id="${i._id}">
	  <div class="wrapper-overlay">
          <img class="gallery-image" src="${i.book_image}" alt="${i.description}">          
			<div class="cat-book-image-overlay">
				<p class="book-image-overlay-text quick-view-trigger">Quick view</p>
			</div>
		</div>
		<h3 class="name-book">${i.title}</h3>
          <p class="author-book">${i.author}</p>
      </li>`).join("");o.insertAdjacentHTML("beforeend",s)}function U(e){const o=document.querySelector(".selected-title"),s=e.split(" "),i=s[s.length-1];s.pop(),o.innerHTML=`${s.join(" ")} <span class="selected-color">${i} </span>`}const h={galleryBooks:document.querySelector(".js-gallery-books"),btnMore:document.querySelector(".btn-more"),listCategoryTitle:document.querySelector(".list-category-title"),allListCategories:document.querySelector(".js-books-categories"),categoryItems:document.querySelectorAll(".category-books-item"),scrollTop:document.getElementById("scrollTop")};document.addEventListener("DOMContentLoaded",()=>{async function e(){const o=await f("category-list");let s='<li data-category="top-books" class="category-books-item">All categories</li>';o.forEach(l=>{s+=`<li class="category-books-item" data-category="${l.list_name}">${l.list_name}</li>`}),h.allListCategories.insertAdjacentHTML("beforeend",s),document.querySelectorAll(".category-books-item").forEach(l=>{l.addEventListener("click",m)});function m(l){l.preventDefault();const p=document.querySelector(".js-home-pg"),t=document.querySelector(".js-selected-page"),n=l.target.innerHTML;for(const d of o)d.list_name===n&&(p.style.display="none",t.style.display="block",D(n));n==="All categories"&&(p.style.display="block",t.style.display="none")}}e()});function v(e){z.error({title:"Error",message:e})}document.addEventListener("DOMContentLoaded",()=>{let e=window.innerWidth;window.addEventListener("resize",async()=>{const t=window.innerWidth;if(e>768||e<768&&t>=768||e>=768&&t<=1440&&(e<=768||t>=1439))try{const n=await f("top-books");h.galleryBooks.innerHTML="";for(const d of n)s(d),d.books.length>=1?l(d):v("Sorry, there are no items in this category")}catch(n){v(`Failed to render books:${n}`)}e=t});async function o(){try{let y=function(c){const k=document.querySelector(".js-home-pg"),g=document.querySelector(".js-selected-page"),E=c.srcElement.dataset.id;k.style.display="none",g.style.display="block",D(E)};const t=await f("top-books");for(const c of t)s(c),c.books.length>=1?l(c):v("Sorry, there are no items in this category");document.querySelectorAll(".book-image-overlay").forEach(c=>{c.addEventListener("click",k=>{const g=k.target.closest(".card");if(g){const E=g.dataset.id;j(E)}})}),document.querySelectorAll(".btn-more").forEach(c=>{c.addEventListener("click",y)})}catch(t){v(`Failed to render books:${t}`)}}function s(t){const n=`<li id="${t.list_name}" class="list-category-books">
    <h2 class="list-category-title">${t.list_name}</h2>
    <ul class="list-book">
     </ul>
    <button type="button" class="btn-more" data-id="${t.list_name}">See more</button>`;h.galleryBooks.insertAdjacentHTML("beforeend",n)}function i(t){const{book_image:n,author:d,title:y,_id:c,contributor:k,list_name:g}=t;if(g)return`
    <li class="card book-item book-hover" data-id="${c}">
       <div class="wrapper-overlay">
        <img class="book-img-home" src="${n}" alt="${k} ${y}">
        <div class="book-image-overlay" aria-label="${y}">
            <p class="book-image-overlay-text quick-view-trigger">Quick view</p>
        </div>
       </div>
    <h3 class="title-book">${y}</h3>
    <p class="author">${d}</p>
    </li>
    `}function m(t){return t.map(i).join("")}function l(t){const n=p(t),d=t.list_name;document.getElementById(d).querySelector(".list-book").insertAdjacentHTML("afterbegin",n)}function p(t){let n;return window.innerWidth>=768&&window.innerWidth<=1439?n=m(t.books.slice(0,3)):window.innerWidth>=1440?n=m(t.books):n=m(t.books.slice(0,1)),n}o()});window.onscroll=()=>{window.scrollY>400?h.scrollTop.classList.remove("isShowScroll_hide"):window.scrollY<400&&h.scrollTop.classList.add("isShowScroll_hide")};h.scrollTop.addEventListener("click",()=>window.scrollTo(0,0));document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".js-hhome a"),o=document.querySelector(".hshopping-link");window.location.pathname==="/index.html"||window.location.pathname==="/"?(e.classList.add("active"),o.classList.remove("active")):(o.classList.add("active"),e.classList.remove("active"))});
//# sourceMappingURL=commonHelpers.js.map
