import { getBooks } from './js/API/api-books';
import './js/API/modal';
import './js/switch-button';
import { render } from './js/API/home';
import './js/NZheader';
import './js/test';
import './js/modalwindow';
import './js/add-removebook';
import './js/storage';
render();
